name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches: [main]
    paths: ["frontend/**"]

env:
  AWS_REGION: us-east-1
  S3_BUCKET: untitled-frontend-prod # This should match your terraform output
  CLOUDFRONT_DISTRIBUTION_ID: # You'll need to get this from terraform output

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build application
        working-directory: frontend
        run: npm run build
        env:
          # Add any build-time environment variables here
          NODE_ENV: production

      - name: Deploy to S3
        working-directory: frontend
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete --exact-timestamps
